
name: Build and deploy

on:
  push:
    branches: 
      - 'PROD'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup trunk
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo install --locked trunk
    - run: rustup target add wasm32-unknown-unknown
    - name: Setup node js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build-node
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist 
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
