
name: Build and deploy

on:
  push:
    branches: [ "PROD" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup trunk
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo install --locked trunk
    - name: Setup node js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build-node
